pipeline {
    agent any

    environment {
        home_dir = '/var/jenkins_home/workspace/bigdata_miniproject_api'
        private_registry = "harbor.kcnet.bigdata.com:30443/bigdata"
        image_name = "bigdata_miniproject_api"
        reg_cred = "harbor_cred"
    }


    stages {
        stage('Init') {
            steps{
                workspace = pwd
                script {
                    echo "${workspace}"
                    docker.withRegistry("${private_registry}") {
                        docker_image = docker.build("${image_name}:latest", "--no-cache ${workspace}/deploy/docker")
                        docker_image.push()
                    }
                }
            }
        }
//
//         stage('Bulid Docker') {
//             steps{
//                 script {
//                     docker_image = docker.build("${image_name}:latest", "--no-cache ./deploy/docker")
//                 }
//                 echo "docker build completed!!!"
//             }
//         }
//
//         stage('Push Docker'){
//             steps {
//                 script {
//                     docker_image.push()
//                 }
//                 echo "docker image push completed"
//             }
//         }
    }
}