pipeline {
    agent any

    environment {
        pipeline_name = 'bigdata_miniproject_api'
        private_registry = "https://harbor.kcnet.bigdata.com:30443"
        image_name = "bigdata_miniproject_api"
        reg_cred = "regcred"
    }

    stages {
        stage('Build & Push Docker image') {
            steps{
                script {
                    docker.withRegistry(private_registry, reg_cred) {
                        docker_image = docker.build("bigdata/${image_name}:latest", "--no-cache ${workspace}/deploy/docker")
                        docker_image.push()
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    echo "${workspace}"
                    echo "Deploy deployment.yaml"
                    sh "kubectl apply -f ${workspace}/deploy/kubernetes/deployment.yaml"

                    echo "Deploy service.yaml"
                    sh "kubectl apply -f ${workspace}/deploy/kubernetes/service.yaml"

                    echo "Deploy ingress.yaml"
                    sh "kubectl apply -f ${workspace}/deploy/kubernetes/ingress.yaml"
                }
            }
        }
    }
}