pipeline {
    agent any
    tools {
      'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'docker'
    }

    environment {
        home_dir = '/var/jenkins_home/workspace/bigdata_miniproject_api'
        private_registry = "harbor.kcnet.bigdata.com:30443/bigdata"
        image_name = "bigdata_miniproject_api"
        reg_cred = "harbor-cred"
//         workspace = "${pwd}"
    }

    stages {
        stage('Init') {
            steps{
                script {
                    sh "docker version"
                    docker.withRegistry(private_registry, reg_cred) {
                        docker_image = docker.build("${image_name}:latest", "--no-cache ${workspace}/deploy/docker")
                        docker_image.push()
                    }
                }
            }
        }
//
//         stage('Bulid Docker') {
//             steps{
//                 script {
//                     docker_image = docker.build("${image_name}:latest", "--no-cache ./deploy/docker")
//                 }
//                 echo "docker build completed!!!"
//             }
//         }
//
//         stage('Push Docker'){
//             steps {
//                 script {
//                     docker_image.push()
//                 }
//                 echo "docker image push completed"
//             }
//         }
    }
}