apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdata_miniproject_api_deploy
  namespace: bigdata-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bigdata_miniproject_api
  template:
    metadata:
      labels:
        app: bigdata_miniproject_api
    spec:
      containers:
        - name: bigdata_miniproject_api
          image: harbor.kcnet.bigdata.com:30443/bigdata/bigdata_miniproject_api:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: harbor-registry