apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bigdata-miniproject-api-ing
  namespace: bigdata-team
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: bmapi.kcnet.bigdata.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bigdata-miniproject-api-svc
            port:
              number: 80