apiVersion: v1
kind: Service
metadata:
  name: bigdata-miniproject-api-svc
  namespace: bigdata-team
spec:
  selector:
    app: bigdata-miniproject-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
